return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "cmake",
      "diff",
      "dockerfile",
      -- "git-config",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "help",
      "html",
      "ini",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "qmldir",
      "qmljs",
      "query",
      "regex",
      "rust",
      "vim",
      "yaml",
    },
    sync_install = true,
  },
}
