add_newline = true

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $package\
  $python\
  $env_var\
  $line_break\
  $cmd_duration\
  $jobs\
  $character\
  """

[cmd_duration]
min_time = 1000
show_milliseconds = true
format = "took [$duration]($style) "

[directory]
truncation_length = 0
truncate_to_repo = true
read_only = " " # 
disabled = false

[hostname]
ssh_only = true
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[line_break]
disabled = false

[python]
symbol = " "
pyenv_version_name = false
pyenv_prefix = "pyenv"
style = "bold yellow"
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style)@"
show_always = false
disabled = false
