#!/usr/bin/env bash

####
# ls
####

alias ls='ls --color=auto'
alias l='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias lc='ls -CF'

######
# grep
######

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

########
# neovim
########

alias nvim='nvim.appimage'
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias lvim='\vim +"set nowrap|syntax off"'        # fast vim for big files / big oneliner

#####
# git
#####

alias gs='git status'
alias gss='git status -s'
alias ga='git add'
alias gp='git push'
alias gpraise='git blame'
alias gpo='git push origin'
alias gpof='git push origin --force-with-lease'
alias gpt='git push --tag'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias grb='git branch -r'                         # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log --pretty=oneline'
alias gr='git remote'
alias grs='git remote show'
alias glol='git log --graph --abbrev-commit --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d"    # Delete local branch merged with master
alias gblog="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:red)%(refname:short)%(color:reset) - %(color:yellow)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:blue)%(committerdate:relative)%(color:reset))'"   # git log for each branches
alias gsub="git submodule update --remote"       # pull submodules
alias gj="git-jump"                              # Open in vim quickfix list files of interest (git diff, merged...)

alias dif="git diff --no-index"                  # Diff two files even if not in git repo! Can add -w (don't diff whitespaces)

######
# tmux
######

alias tmuxk='tmux kill-session -t'
alias tmuxa='tmux attach -t'
alias tmuxl='tmux list-sessions'

#######
# tmuxp
#######

alias mux='tmuxp load'

########
# docker
########

# alias dockls="docker container ls | awk 'NR > 1 {print \$NF}'"                  # display names of running containers
# alias dockRr='docker rm $(docker ps -a -q)'                                     # delete every containers / images
# alias dockRr='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
# alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
# alias dockimg='docker images'                                                   # list images installed
# alias dockprune='docker system prune -a'                                        # prune everything
# alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
# alias dockce='docker-compose run --rm'

